/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/16/24, 11:01 AM' 
 * Generated by 'cheta' 
 * Generated on server 'CK.HSD1.CT.COMCAST.NET' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:51322/main?locale=en_US&zone=GMT-05%253A00&sutoken=%257BC0C9088F-F9A9-4F80-82A3-D0020C14167A%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=PROJECT1.AIRTRAFFIC1 out=Work.preProcessedData;
	by Date;
run;

proc timeseries data=Work.preProcessedData seasonality=12 plots=(series cycles 
		corr decomp tc tcc sc ic) crossplots=(series ccf);
	id Date interval=month;
	var RPM / accumulate=none transform=none dif=0 sdif=0;
	crossvar Pax / accumulate=none transform=none dif=0 sdif=0;
	crossvar Flt / accumulate=none transform=none dif=0 sdif=0;
	crossvar ASM / accumulate=none transform=none dif=0 sdif=0;
	crossvar LF / accumulate=none transform=none dif=0 sdif=0;
	crossvar RAMP / accumulate=none transform=none dif=0 sdif=0;
	decomp tc trendcycle seasonal irregular / mode=multoradd;
	ods exclude CCFNORMPlot;
run;

/* Unit root test analysis */
proc arima data=Work.preProcessedData plots=none;
	ods select StationarityTests;
	identify var=RPM stationarity=(adf=3);
	run;
quit;

proc delete data=Work.preProcessedData;
run;