/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '8/5/21, 5:34 PM' 
 * Generated by 'sudip' 
 * Generated on server 'D10375WSUB02OP2.BUSINESS.UCONN.EDU' 
 * Generated on SAS platform 'X64_10PRO WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.62' 
 * Generated on web client 'http://localhost:53837/main?locale=en_US&zone=GMT-04%253A00&sutoken=%257B75972C09-51B9-4A61-999F-DC452AB7671B%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data= PROJECT1.AIRTRAFFIC1 out=Work.preProcessedData;
	by Date;
run;

proc arima data=Work.preProcessedData plots
     (only)=(series(corr crosscorr) residual(corr normal wn) );
	identify var=ASM(1 12);
	estimate p=(1) q=(12) method=ML;
	identify var=RPM crosscorr=(ASM(1 12));
	estimate input=(ASM(1 12)) method=ML;
	identify var=Flt(1 12);
	estimate p=(1 2) q=(12) method=ML;
	identify var=RPM crosscorr=(Flt(1 12));
	estimate input=(Flt(1 12)) method=ML;
	identify var=LF(1 12);
	estimate p=(1 2) q=(12) method=ML;
	identify var=RPM crosscorr=(LF(1 12));
	estimate input=(LF(1 12)) method=ML;
	identify var=Pax(1 12);
	estimate p=(1) q=(12) method=ML;
	identify var=RPM crosscorr=(Pax(1 12));
	estimate input=(Pax(1 12)) method=ML;
	run;
quit;

proc delete data=Work.preProcessedData;
run;