/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/17/24, 1:21 PM' 
 * Generated by 'cheta' 
 * Generated on server 'CK.HSD1.CT.COMCAST.NET' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:51322/main?locale=en_US&zone=GMT-05%253A00&sutoken=%257BC0C9088F-F9A9-4F80-82A3-D0020C14167A%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=PROJECT1.AIRTRAFFIC_F1 out=Work.preProcessedData;
	by Date;
run;

proc arima data=Work.preProcessedData plots
     (only)=(series(corr crosscorr) residual(corr normal wn) 
		forecast(forecast forecastonly) ) out=work.out0002;
	identify var=Flt(1 12) crosscorr=(Ramp(1 12) ) outcov=work.outcov0002;
	estimate p=(1 2) q=(12) input=(Ramp) method=ML outest=work.outest0002 
		outstat=work.outstat0002;
	forecast lead=12 back=0 alpha=0.05 id=Date interval=month printall;
	run;
quit;

proc delete data=Work.preProcessedData;
run;